/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shtruz_externalfinalscounter_instrument_Instrumentation */

#ifndef _Included_com_shtruz_externalfinalscounter_instrument_Instrumentation
#define _Included_com_shtruz_externalfinalscounter_instrument_Instrumentation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shtruz_externalfinalscounter_instrument_Instrumentation
 * Method:    retransformClass
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_shtruz_externalfinalscounter_instrument_Instrumentation_retransformClass
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
