/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shtruz_externalfinalscounter_ExternalFinalsCounter */

#ifndef _Included_com_shtruz_externalfinalscounter_ExternalFinalsCounter
#define _Included_com_shtruz_externalfinalscounter_ExternalFinalsCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shtruz_externalfinalscounter_ExternalFinalsCounter
 * Method:    initialize
 * Signature: (Ljava/lang/ClassLoader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_shtruz_externalfinalscounter_ExternalFinalsCounter_initialize
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
